-- Actividades para casa, entregas y notificaciones push.

create table public.actividades_aprendizaje (
    id bigint generated by default as identity primary key,
    institucion_id bigint not null references public.instituciones_educativas(id),
    anio_escolar_id bigint not null references public.anios_escolares(id),
    experiencia_id bigint references public.experiencias_aprendizaje(id),
    sesion_planificada_id bigint references public.sesiones_planificadas(id),
    area_curricular_id bigint references public.areas_curriculares(id),
    titulo varchar(240) not null,
    instrucciones text not null,
    tipo varchar(30) not null default 'OTRA'
        check (tipo in ('LECTURA', 'PRACTICA', 'FICHA', 'PROYECTO', 'OBSERVACION', 'OTRA')),
    formato_entrega varchar(24) not null default 'NO_REQUIERE'
        check (formato_entrega in ('NO_REQUIERE', 'ARCHIVO', 'PAPEL', 'ORAL', 'EN_CLASE', 'OTRO')),
    requiere_entrega boolean not null default false,
    publicada_at timestamptz,
    fecha_limite timestamptz,
    estado varchar(20) not null default 'BORRADOR'
        check (estado in ('BORRADOR', 'PUBLICADA', 'CERRADA', 'ANULADA')),
    creada_por bigint not null references public.cuentas_usuario(id),
    created_at timestamptz not null default now(),
    check (fecha_limite is null or publicada_at is null or fecha_limite >= publicada_at),
    check ((requiere_entrega and formato_entrega <> 'NO_REQUIERE') or
           (not requiere_entrega and formato_entrega = 'NO_REQUIERE'))
);

create table public.destinos_actividad (
    id bigint generated by default as identity primary key,
    actividad_id bigint not null references public.actividades_aprendizaje(id),
    seccion_id bigint references public.secciones(id),
    matricula_id bigint references public.matriculas(id),
    check (num_nonnulls(seccion_id, matricula_id) = 1),
    unique nulls not distinct (actividad_id, seccion_id, matricula_id)
);

create table public.asignaciones_actividad (
    id bigint generated by default as identity primary key,
    actividad_id bigint not null references public.actividades_aprendizaje(id),
    matricula_id bigint not null references public.matriculas(id),
    estado varchar(32) not null default 'PENDIENTE'
        check (estado in (
            'PENDIENTE', 'ENTREGADA', 'ENTREGADA_TARDE', 'REVISADA',
            'NO_ENTREGADA_CONFIRMADA', 'EXENTA', 'NO_REQUIERE_ENTREGA'
        )),
    estado_confirmado_por bigint references public.cuentas_usuario(id),
    estado_confirmado_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check ((estado = 'NO_ENTREGADA_CONFIRMADA' and estado_confirmado_por is not null)
           or estado <> 'NO_ENTREGADA_CONFIRMADA'),
    unique (actividad_id, matricula_id)
);

create table public.archivos (
    id bigint generated by default as identity primary key,
    bucket varchar(80) not null,
    ruta_objeto text not null,
    nombre_original varchar(255) not null,
    tipo_contenido varchar(120),
    tamano_bytes bigint check (tamano_bytes is null or tamano_bytes >= 0),
    creado_por bigint references public.cuentas_usuario(id),
    created_at timestamptz not null default now(),
    unique (bucket, ruta_objeto)
);

create table public.entregas_actividad (
    id bigint generated by default as identity primary key,
    asignacion_actividad_id bigint not null references public.asignaciones_actividad(id),
    numero_intento smallint not null default 1 check (numero_intento > 0),
    formato varchar(24) not null check (formato in ('ARCHIVO', 'PAPEL', 'ORAL', 'EN_CLASE', 'OTRO')),
    contenido text,
    archivo_id bigint references public.archivos(id),
    registrada_por bigint not null references public.cuentas_usuario(id),
    entregada_at timestamptz not null default now(),
    unique (asignacion_actividad_id, numero_intento)
);

create table public.revisiones_actividad (
    id bigint generated by default as identity primary key,
    entrega_id bigint not null references public.entregas_actividad(id),
    revisada_por bigint not null references public.cuentas_usuario(id),
    comentario text,
    revisada_at timestamptz not null default now()
);

create table public.tipos_notificacion (
    id smallint generated by default as identity primary key,
    codigo varchar(40) not null unique,
    nombre varchar(120) not null,
    activa boolean not null default true
);

insert into public.tipos_notificacion (codigo, nombre) values
    ('AUSENCIA_CONFIRMADA', 'Ausencia confirmada'),
    ('CORRECCION_ASISTENCIA', 'Corrección de asistencia'),
    ('ACTIVIDAD_PUBLICADA', 'Actividad publicada'),
    ('ACTIVIDAD_POR_VENCER', 'Actividad por vencer'),
    ('NO_ENTREGA_CONFIRMADA', 'No entrega confirmada por docente'),
    ('AVISO_INSTITUCIONAL', 'Aviso institucional');

create table public.preferencias_notificacion (
    id bigint generated by default as identity primary key,
    cuenta_usuario_id bigint not null references public.cuentas_usuario(id),
    tipo_notificacion_id smallint not null references public.tipos_notificacion(id),
    canal varchar(24) not null check (canal in ('ANDROID_PUSH', 'WEB_PUSH', 'EMAIL', 'SMS')),
    habilitada boolean not null default true,
    hora_silencio_inicio time,
    hora_silencio_fin time,
    unique (cuenta_usuario_id, tipo_notificacion_id, canal)
);

create table public.dispositivos_notificacion (
    id bigint generated by default as identity primary key,
    cuenta_usuario_id bigint not null references public.cuentas_usuario(id),
    plataforma varchar(20) not null check (plataforma in ('ANDROID', 'WEB', 'IOS')),
    token_registro text not null unique,
    permiso_habilitado boolean not null default true,
    activo boolean not null default true,
    ultimo_uso_at timestamptz,
    registrado_at timestamptz not null default now(),
    revocado_at timestamptz
);

create table public.eventos_notificacion (
    id bigint generated by default as identity primary key,
    tipo_notificacion_id smallint not null references public.tipos_notificacion(id),
    registro_asistencia_id bigint references public.registros_asistencia(id),
    actividad_id bigint references public.actividades_aprendizaje(id),
    asignacion_actividad_id bigint references public.asignaciones_actividad(id),
    version_origen integer not null default 1 check (version_origen > 0),
    clave_idempotencia varchar(180) not null unique,
    datos_minimos jsonb not null default '{}'::jsonb,
    estado varchar(20) not null default 'PENDIENTE'
        check (estado in ('PENDIENTE', 'PROCESANDO', 'PROCESADO', 'FALLIDO', 'CANCELADO')),
    creado_at timestamptz not null default now(),
    procesado_at timestamptz,
    check (num_nonnulls(registro_asistencia_id, actividad_id, asignacion_actividad_id) = 1)
);

create table public.notificaciones (
    id bigint generated by default as identity primary key,
    evento_id bigint not null references public.eventos_notificacion(id),
    vinculo_apoderado_estudiante_id bigint not null references public.vinculos_apoderado_estudiante(id),
    cuenta_destinataria_id bigint references public.cuentas_usuario(id),
    titulo varchar(180) not null,
    mensaje varchar(500) not null,
    ruta_destino text,
    creada_at timestamptz not null default now(),
    leida_at timestamptz,
    unique (evento_id, vinculo_apoderado_estudiante_id)
);

create table public.entregas_notificacion (
    id bigint generated by default as identity primary key,
    notificacion_id bigint not null references public.notificaciones(id),
    dispositivo_id bigint references public.dispositivos_notificacion(id),
    canal varchar(24) not null check (canal in ('ANDROID_PUSH', 'WEB_PUSH', 'EMAIL', 'SMS')),
    estado varchar(20) not null default 'EN_COLA'
        check (estado in ('EN_COLA', 'ACEPTADA', 'ENTREGADA', 'FALLIDA', 'EXPIRADA', 'CANCELADA')),
    proveedor varchar(40),
    identificador_proveedor varchar(180),
    expira_at timestamptz,
    aceptada_at timestamptz,
    entregada_at timestamptz,
    ultimo_error text,
    unique (notificacion_id, dispositivo_id, canal)
);

create table public.intentos_notificacion (
    id bigint generated by default as identity primary key,
    entrega_notificacion_id bigint not null references public.entregas_notificacion(id),
    numero_intento smallint not null check (numero_intento > 0),
    resultado varchar(20) not null check (resultado in ('ACEPTADO', 'ENTREGADO', 'FALLIDO')),
    codigo_respuesta varchar(100),
    detalle text,
    intentado_at timestamptz not null default now(),
    unique (entrega_notificacion_id, numero_intento)
);

create table public.eventos_auditoria (
    id bigint generated by default as identity primary key,
    cuenta_usuario_id bigint references public.cuentas_usuario(id),
    institucion_id bigint references public.instituciones_educativas(id),
    tipo_evento varchar(80) not null,
    tipo_objeto varchar(80) not null,
    objeto_id bigint not null,
    datos_minimos jsonb not null default '{}'::jsonb,
    ocurrido_at timestamptz not null default now()
);

-- Los clientes no consultan Postgres directamente. El backend es el único acceso
-- de aplicación; se habilita RLS y no se conceden permisos al API anon/authenticated.
do $$
declare
    tabla record;
begin
    for tabla in
        select tablename
        from pg_tables
        where schemaname = 'public'
          and tablename in (
              'instituciones_educativas', 'sedes_educativas', 'niveles_educativos',
              'ciclos_educativos', 'grados_educativos', 'turnos', 'anios_escolares',
              'periodos_evaluacion', 'aulas', 'personas', 'cuentas_usuario', 'roles',
              'estudiantes', 'apoderados', 'contactos_persona', 'niveles_notificacion',
              'secciones', 'asignaciones_roles', 'vinculos_apoderado_estudiante',
              'matriculas', 'ubicaciones_matricula', 'movimientos_matricula',
              'asignaciones_docentes', 'jornadas_asistencia', 'registros_asistencia',
              'versiones_curriculares', 'areas_curriculares', 'version_areas_curriculares',
              'competencias', 'competencias_areas', 'capacidades', 'estandares_aprendizaje',
              'desempenos_grado', 'planes_estudio', 'planes_estudio_areas',
              'ofertas_curriculares', 'asignaciones_docentes_areas', 'eventos_calendario',
              'planificaciones_anuales', 'destinos_planificacion', 'experiencias_aprendizaje',
              'experiencias_competencias', 'criterios_evaluacion', 'instrumentos_evaluacion',
              'criterios_instrumento', 'niveles_instrumento', 'sesiones_planificadas',
              'sesiones_competencias', 'actividades_sesion', 'evidencias_previstas',
              'ejecuciones_sesion', 'evidencias_aprendizaje', 'valoraciones_evidencia',
              'retroalimentaciones', 'progreso_competencias', 'actividades_aprendizaje',
              'destinos_actividad', 'asignaciones_actividad', 'archivos', 'entregas_actividad',
              'revisiones_actividad', 'tipos_notificacion', 'preferencias_notificacion',
              'dispositivos_notificacion', 'eventos_notificacion', 'notificaciones',
              'entregas_notificacion', 'intentos_notificacion',
              'eventos_auditoria'
          )
    loop
        execute format('alter table public.%I enable row level security', tabla.tablename);
    end loop;
end $$;

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'anon') then
        execute 'revoke all on all tables in schema public from anon';
        execute 'revoke all on all sequences in schema public from anon';
    end if;
    if exists (select 1 from pg_roles where rolname = 'authenticated') then
        execute 'revoke all on all tables in schema public from authenticated';
        execute 'revoke all on all sequences in schema public from authenticated';
    end if;
end $$;
