-- Currículo versionado, planificación anual, unidades/experiencias, sesiones y evaluación.

create table public.versiones_curriculares (
    id bigint generated by default as identity primary key,
    codigo varchar(40) not null unique,
    nombre varchar(180) not null,
    fuente_url text,
    vigente_desde date,
    vigente_hasta date,
    check (vigente_hasta is null or vigente_desde is null or vigente_hasta >= vigente_desde)
);

create table public.areas_curriculares (
    id bigint generated by default as identity primary key,
    codigo varchar(40) not null unique,
    nombre varchar(120) not null,
    activa boolean not null default true
);

create table public.version_areas_curriculares (
    id bigint generated by default as identity primary key,
    version_curricular_id bigint not null references public.versiones_curriculares(id),
    area_curricular_id bigint not null references public.areas_curriculares(id),
    nivel_id smallint references public.niveles_educativos(id),
    unique nulls not distinct (version_curricular_id, area_curricular_id, nivel_id)
);

create table public.competencias (
    id bigint generated by default as identity primary key,
    version_curricular_id bigint not null references public.versiones_curriculares(id),
    codigo varchar(60) not null,
    nombre varchar(240) not null,
    tipo varchar(20) not null default 'AREA'
        check (tipo in ('AREA', 'TRANSVERSAL')),
    unique (version_curricular_id, codigo)
);

create table public.competencias_areas (
    competencia_id bigint not null references public.competencias(id),
    area_curricular_id bigint not null references public.areas_curriculares(id),
    primary key (competencia_id, area_curricular_id)
);

create table public.capacidades (
    id bigint generated by default as identity primary key,
    competencia_id bigint not null references public.competencias(id),
    codigo varchar(60),
    nombre varchar(240) not null,
    orden smallint not null default 1,
    unique (competencia_id, orden)
);

create table public.estandares_aprendizaje (
    id bigint generated by default as identity primary key,
    competencia_id bigint not null references public.competencias(id),
    ciclo_id smallint not null references public.ciclos_educativos(id),
    descripcion text not null,
    unique (competencia_id, ciclo_id)
);

create table public.desempenos_grado (
    id bigint generated by default as identity primary key,
    competencia_id bigint not null references public.competencias(id),
    grado_id smallint not null references public.grados_educativos(id),
    descripcion text not null,
    fuente_url text,
    unique (competencia_id, grado_id, descripcion)
);

create table public.planes_estudio (
    id bigint generated by default as identity primary key,
    version_curricular_id bigint not null references public.versiones_curriculares(id),
    grado_id smallint not null references public.grados_educativos(id),
    codigo_modelo_servicio varchar(40) not null default 'EBR_REGULAR',
    nombre varchar(180) not null,
    unique (version_curricular_id, grado_id, codigo_modelo_servicio)
);

create table public.planes_estudio_areas (
    id bigint generated by default as identity primary key,
    plan_estudio_id bigint not null references public.planes_estudio(id),
    area_curricular_id bigint not null references public.areas_curriculares(id),
    horas_pedagogicas smallint check (horas_pedagogicas is null or horas_pedagogicas >= 0),
    es_obligatoria boolean not null default true,
    unique (plan_estudio_id, area_curricular_id)
);

create table public.ofertas_curriculares (
    id bigint generated by default as identity primary key,
    seccion_id bigint not null references public.secciones(id),
    area_curricular_id bigint not null references public.areas_curriculares(id),
    plan_estudio_area_id bigint references public.planes_estudio_areas(id),
    activa boolean not null default true,
    unique (seccion_id, area_curricular_id)
);

create table public.asignaciones_docentes_areas (
    id bigint generated by default as identity primary key,
    oferta_curricular_id bigint not null references public.ofertas_curriculares(id),
    cuenta_usuario_id bigint not null references public.cuentas_usuario(id),
    vigente_desde date not null default current_date,
    vigente_hasta date,
    check (vigente_hasta is null or vigente_hasta >= vigente_desde),
    unique (oferta_curricular_id, cuenta_usuario_id, vigente_desde)
);

create table public.eventos_calendario (
    id bigint generated by default as identity primary key,
    anio_escolar_id bigint not null references public.anios_escolares(id),
    nombre varchar(180) not null,
    tipo varchar(30) not null check (tipo in (
        'LECTIVO', 'GESTION', 'VACACIONES', 'FERIADO', 'SUSPENSION', 'RECUPERACION', 'OTRO'
    )),
    fecha_inicio date not null,
    fecha_fin date not null,
    descripcion text,
    check (fecha_fin >= fecha_inicio)
);

create table public.planificaciones_anuales (
    id bigint generated by default as identity primary key,
    institucion_id bigint not null references public.instituciones_educativas(id),
    anio_escolar_id bigint not null references public.anios_escolares(id),
    nombre varchar(180) not null,
    version smallint not null default 1 check (version > 0),
    estado varchar(20) not null default 'BORRADOR'
        check (estado in ('BORRADOR', 'PUBLICADA', 'ARCHIVADA')),
    creada_por bigint not null references public.cuentas_usuario(id),
    creada_at timestamptz not null default now(),
    actualizada_at timestamptz not null default now(),
    unique (institucion_id, anio_escolar_id, nombre, version)
);

create table public.destinos_planificacion (
    id bigint generated by default as identity primary key,
    planificacion_anual_id bigint not null references public.planificaciones_anuales(id),
    grado_id smallint references public.grados_educativos(id),
    seccion_id bigint references public.secciones(id),
    area_curricular_id bigint references public.areas_curriculares(id),
    check (grado_id is not null or seccion_id is not null),
    unique nulls not distinct (planificacion_anual_id, grado_id, seccion_id, area_curricular_id)
);

create table public.experiencias_aprendizaje (
    id bigint generated by default as identity primary key,
    planificacion_anual_id bigint not null references public.planificaciones_anuales(id),
    tipo varchar(24) not null check (tipo in ('UNIDAD', 'PROYECTO', 'EXPERIENCIA', 'MODULO', 'OTRA')),
    titulo varchar(240) not null,
    situacion_significativa text,
    proposito text,
    fecha_inicio date,
    fecha_fin date,
    numero_orden smallint not null check (numero_orden > 0),
    estado varchar(20) not null default 'BORRADOR'
        check (estado in ('BORRADOR', 'PUBLICADA', 'EN_CURSO', 'FINALIZADA', 'ARCHIVADA')),
    created_at timestamptz not null default now(),
    check (fecha_fin is null or fecha_inicio is null or fecha_fin >= fecha_inicio),
    unique (planificacion_anual_id, numero_orden)
);

create table public.experiencias_competencias (
    experiencia_id bigint not null references public.experiencias_aprendizaje(id),
    competencia_id bigint not null references public.competencias(id),
    proposito_especifico text,
    primary key (experiencia_id, competencia_id)
);

create table public.experiencias_periodos (
    experiencia_id bigint not null references public.experiencias_aprendizaje(id),
    periodo_evaluacion_id bigint not null references public.periodos_evaluacion(id),
    primary key (experiencia_id, periodo_evaluacion_id)
);

create table public.horarios_seccion (
    id bigint generated by default as identity primary key,
    seccion_id bigint not null references public.secciones(id),
    oferta_curricular_id bigint references public.ofertas_curriculares(id),
    dia_semana smallint not null check (dia_semana between 1 and 7),
    hora_inicio time not null,
    hora_fin time not null,
    descripcion varchar(120),
    vigente_desde date not null default current_date,
    vigente_hasta date,
    check (hora_fin > hora_inicio),
    check (vigente_hasta is null or vigente_hasta >= vigente_desde),
    unique (seccion_id, dia_semana, hora_inicio)
);

create table public.criterios_evaluacion (
    id bigint generated by default as identity primary key,
    experiencia_id bigint not null references public.experiencias_aprendizaje(id),
    competencia_id bigint not null references public.competencias(id),
    descripcion text not null,
    orden smallint not null default 1,
    unique (experiencia_id, competencia_id, orden)
);

create table public.instrumentos_evaluacion (
    id bigint generated by default as identity primary key,
    experiencia_id bigint not null references public.experiencias_aprendizaje(id),
    nombre varchar(180) not null,
    tipo varchar(30) not null check (tipo in ('RUBRICA', 'LISTA_COTEJO', 'REGISTRO', 'PORTAFOLIO', 'OTRO')),
    descripcion text,
    created_at timestamptz not null default now()
);

create table public.criterios_instrumento (
    id bigint generated by default as identity primary key,
    instrumento_id bigint not null references public.instrumentos_evaluacion(id),
    criterio_id bigint references public.criterios_evaluacion(id),
    descripcion text not null,
    orden smallint not null default 1,
    unique (instrumento_id, orden)
);

create table public.niveles_instrumento (
    id bigint generated by default as identity primary key,
    criterio_instrumento_id bigint not null references public.criterios_instrumento(id),
    codigo varchar(30) not null,
    descripcion text not null,
    orden smallint not null,
    unique (criterio_instrumento_id, codigo),
    unique (criterio_instrumento_id, orden)
);

create table public.sesiones_planificadas (
    id bigint generated by default as identity primary key,
    experiencia_id bigint references public.experiencias_aprendizaje(id),
    numero_orden smallint,
    titulo varchar(240) not null,
    proposito text,
    duracion_minutos smallint check (duracion_minutos is null or duracion_minutos > 0),
    estado varchar(20) not null default 'BORRADOR'
        check (estado in ('BORRADOR', 'PUBLICADA', 'ARCHIVADA')),
    created_at timestamptz not null default now(),
    check ((experiencia_id is null and numero_orden is null) or
           (experiencia_id is not null and numero_orden > 0))
);

create unique index uq_sesion_orden_en_experiencia
    on public.sesiones_planificadas (experiencia_id, numero_orden)
    where experiencia_id is not null;

create table public.sesiones_competencias (
    sesion_id bigint not null references public.sesiones_planificadas(id),
    competencia_id bigint not null references public.competencias(id),
    primary key (sesion_id, competencia_id)
);

create table public.actividades_sesion (
    id bigint generated by default as identity primary key,
    sesion_id bigint not null references public.sesiones_planificadas(id),
    numero_orden smallint not null check (numero_orden > 0),
    momento varchar(20) check (momento in ('INICIO', 'DESARROLLO', 'CIERRE', 'OTRO')),
    titulo varchar(180),
    instrucciones text not null,
    duracion_minutos smallint check (duracion_minutos is null or duracion_minutos > 0),
    unique (sesion_id, numero_orden)
);

create table public.evidencias_previstas (
    id bigint generated by default as identity primary key,
    experiencia_id bigint not null references public.experiencias_aprendizaje(id),
    sesion_id bigint references public.sesiones_planificadas(id),
    descripcion text not null,
    formato varchar(30) check (formato in ('ORAL', 'ESCRITA', 'OBSERVACION', 'ARCHIVO', 'PRODUCTO', 'OTRO')),
    requiere_entrega boolean not null default false
);

create table public.ejecuciones_sesion (
    id bigint generated by default as identity primary key,
    sesion_planificada_id bigint references public.sesiones_planificadas(id),
    seccion_id bigint not null references public.secciones(id),
    cuenta_docente_id bigint not null references public.cuentas_usuario(id),
    fecha date not null,
    hora_inicio time,
    hora_fin time,
    estado varchar(20) not null default 'REALIZADA'
        check (estado in ('REALIZADA', 'PARCIAL', 'CANCELADA', 'REPROGRAMADA')),
    motivo_cambio text,
    created_at timestamptz not null default now(),
    check (hora_fin is null or hora_inicio is null or hora_fin > hora_inicio)
);

create table public.evidencias_aprendizaje (
    id bigint generated by default as identity primary key,
    ejecucion_sesion_id bigint not null references public.ejecuciones_sesion(id),
    matricula_id bigint not null references public.matriculas(id),
    tipo varchar(30) not null check (tipo in ('ORAL', 'ESCRITA', 'OBSERVACION', 'ARCHIVO', 'PRODUCTO', 'OTRO')),
    descripcion text,
    ubicacion_archivo text,
    recogida_at timestamptz not null default now(),
    recogida_por bigint not null references public.cuentas_usuario(id)
);

create table public.valoraciones_evidencia (
    id bigint generated by default as identity primary key,
    evidencia_id bigint not null references public.evidencias_aprendizaje(id),
    criterio_id bigint not null references public.criterios_evaluacion(id),
    nivel_instrumento_id bigint references public.niveles_instrumento(id),
    observacion text,
    valorada_por bigint not null references public.cuentas_usuario(id),
    valorada_at timestamptz not null default now(),
    unique (evidencia_id, criterio_id)
);

create table public.retroalimentaciones (
    id bigint generated by default as identity primary key,
    matricula_id bigint not null references public.matriculas(id),
    evidencia_id bigint references public.evidencias_aprendizaje(id),
    competencia_id bigint references public.competencias(id),
    comentario text not null,
    registrada_por bigint not null references public.cuentas_usuario(id),
    registrada_at timestamptz not null default now(),
    check (evidencia_id is not null or competencia_id is not null)
);

create table public.progreso_competencias (
    id bigint generated by default as identity primary key,
    matricula_id bigint not null references public.matriculas(id),
    competencia_id bigint not null references public.competencias(id),
    periodo_evaluacion_id bigint not null references public.periodos_evaluacion(id),
    estado varchar(20) not null default 'PENDIENTE'
        check (estado in ('PENDIENTE', 'EVALUADA', 'POSTERGADA')),
    nivel_logro varchar(2) check (nivel_logro in ('AD', 'A', 'B', 'C')),
    conclusion_descriptiva text,
    recomendacion text,
    registrada_por bigint references public.cuentas_usuario(id),
    registrada_at timestamptz,
    check ((estado = 'EVALUADA' and nivel_logro is not null) or
           (estado <> 'EVALUADA' and nivel_logro is null)),
    unique (matricula_id, competencia_id, periodo_evaluacion_id)
);
