-- EduFast: institución, estructura escolar, identidades, matrícula y asistencia.
-- Ejecutado por Supabase CLI. Los clientes web/móvil no acceden a estas tablas.

create table public.instituciones_educativas (
    id bigint generated by default as identity primary key,
    codigo_modular varchar(20) unique,
    codigo_local varchar(20),
    nombre varchar(180) not null,
    tipo_gestion varchar(20) not null check (tipo_gestion in ('PUBLICA', 'PRIVADA', 'CONVENIO', 'OTRA')),
    created_at timestamptz not null default now()
);

create table public.sedes_educativas (
    id bigint generated by default as identity primary key,
    institucion_id bigint not null references public.instituciones_educativas(id),
    codigo_local varchar(20),
    nombre varchar(180) not null,
    direccion text,
    created_at timestamptz not null default now(),
    unique (institucion_id, nombre)
);

create table public.niveles_educativos (
    id smallint generated by default as identity primary key,
    codigo varchar(20) not null unique,
    nombre varchar(80) not null unique
);

insert into public.niveles_educativos (codigo, nombre) values
    ('PRIMARIA', 'Primaria'),
    ('SECUNDARIA', 'Secundaria');

create table public.ciclos_educativos (
    id smallint generated by default as identity primary key,
    nivel_id smallint not null references public.niveles_educativos(id),
    codigo varchar(10) not null,
    nombre varchar(60) not null,
    unique (nivel_id, codigo)
);

insert into public.ciclos_educativos (nivel_id, codigo, nombre)
select n.id, v.codigo, v.nombre
from public.niveles_educativos n
cross join (values
    ('PRIMARIA', 'III', 'Ciclo III'),
    ('PRIMARIA', 'IV', 'Ciclo IV'),
    ('PRIMARIA', 'V', 'Ciclo V'),
    ('SECUNDARIA', 'VI', 'Ciclo VI'),
    ('SECUNDARIA', 'VII', 'Ciclo VII')
) as v(nivel_codigo, codigo, nombre)
where n.codigo = v.nivel_codigo;

create table public.grados_educativos (
    id smallint generated by default as identity primary key,
    nivel_id smallint not null references public.niveles_educativos(id),
    ciclo_id smallint not null references public.ciclos_educativos(id),
    numero smallint not null check (numero between 1 and 6),
    nombre varchar(40) not null,
    codigo varchar(20) not null unique,
    unique (nivel_id, numero)
);

insert into public.grados_educativos (nivel_id, ciclo_id, numero, nombre, codigo)
select n.id, c.id, v.numero, v.nombre, v.codigo
from (values
    ('PRIMARIA', 'III', 1, '1.º de primaria', 'PRI-01'),
    ('PRIMARIA', 'III', 2, '2.º de primaria', 'PRI-02'),
    ('PRIMARIA', 'IV', 3, '3.º de primaria', 'PRI-03'),
    ('PRIMARIA', 'IV', 4, '4.º de primaria', 'PRI-04'),
    ('PRIMARIA', 'V', 5, '5.º de primaria', 'PRI-05'),
    ('PRIMARIA', 'V', 6, '6.º de primaria', 'PRI-06'),
    ('SECUNDARIA', 'VI', 1, '1.º de secundaria', 'SEC-01'),
    ('SECUNDARIA', 'VI', 2, '2.º de secundaria', 'SEC-02'),
    ('SECUNDARIA', 'VII', 3, '3.º de secundaria', 'SEC-03'),
    ('SECUNDARIA', 'VII', 4, '4.º de secundaria', 'SEC-04'),
    ('SECUNDARIA', 'VII', 5, '5.º de secundaria', 'SEC-05')
) as v(nivel_codigo, ciclo_codigo, numero, nombre, codigo)
join public.niveles_educativos n on n.codigo = v.nivel_codigo
join public.ciclos_educativos c on c.nivel_id = n.id and c.codigo = v.ciclo_codigo;

create table public.turnos (
    id smallint generated by default as identity primary key,
    codigo varchar(20) not null unique,
    nombre varchar(60) not null
);

insert into public.turnos (codigo, nombre) values
    ('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('OTRO', 'Otro');

create table public.anios_escolares (
    id bigint generated by default as identity primary key,
    institucion_id bigint not null references public.instituciones_educativas(id),
    anio smallint not null check (anio between 2000 and 2200),
    fecha_inicio date not null,
    fecha_fin date not null,
    estado varchar(20) not null default 'PLANIFICADO'
        check (estado in ('PLANIFICADO', 'ACTIVO', 'CERRADO')),
    created_at timestamptz not null default now(),
    check (fecha_fin >= fecha_inicio),
    unique (institucion_id, anio)
);

create table public.periodos_evaluacion (
    id bigint generated by default as identity primary key,
    anio_escolar_id bigint not null references public.anios_escolares(id),
    nombre varchar(80) not null,
    tipo varchar(20) not null check (tipo in ('BIMESTRE', 'TRIMESTRE', 'SEMESTRE', 'OTRO')),
    numero smallint not null check (numero > 0),
    fecha_inicio date not null,
    fecha_fin date not null,
    estado varchar(20) not null default 'PLANIFICADO'
        check (estado in ('PLANIFICADO', 'ABIERTO', 'CERRADO')),
    check (fecha_fin >= fecha_inicio),
    unique (anio_escolar_id, tipo, numero)
);

create table public.aulas (
    id bigint generated by default as identity primary key,
    sede_id bigint not null references public.sedes_educativas(id),
    nombre varchar(80) not null,
    aforo_maximo smallint check (aforo_maximo is null or aforo_maximo > 0),
    unique (sede_id, nombre)
);

create table public.personas (
    id bigint generated by default as identity primary key,
    nombres varchar(120) not null,
    apellidos varchar(160) not null,
    tipo_documento varchar(20),
    numero_documento varchar(30),
    fecha_nacimiento date,
    created_at timestamptz not null default now(),
    unique (tipo_documento, numero_documento)
);

create table public.cuentas_usuario (
    id bigint generated by default as identity primary key,
    persona_id bigint not null unique references public.personas(id),
    correo varchar(254) not null unique,
    password_hash varchar(255) not null,
    estado varchar(20) not null default 'ACTIVA'
        check (estado in ('INVITADA', 'ACTIVA', 'BLOQUEADA', 'REVOCADA')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.roles (
    id smallint generated by default as identity primary key,
    codigo varchar(30) not null unique,
    nombre varchar(80) not null
);

insert into public.roles (codigo, nombre) values
    ('DOCENTE', 'Docente'),
    ('DIRECTOR', 'Director'),
    ('APODERADO', 'Apoderado'),
    ('ESTUDIANTE', 'Estudiante'),
    ('ADMINISTRADOR', 'Administrador');

create table public.estudiantes (
    id bigint generated by default as identity primary key,
    persona_id bigint not null unique references public.personas(id),
    codigo_estudiante varchar(40) not null unique,
    identificador_trayectoria varchar(60),
    created_at timestamptz not null default now()
);

create table public.apoderados (
    id bigint generated by default as identity primary key,
    persona_id bigint not null unique references public.personas(id),
    cuenta_usuario_id bigint unique references public.cuentas_usuario(id),
    created_at timestamptz not null default now()
);

create table public.contactos_persona (
    id bigint generated by default as identity primary key,
    persona_id bigint not null references public.personas(id),
    tipo varchar(20) not null check (tipo in ('TELEFONO', 'CORREO')),
    valor varchar(254) not null,
    verificado_at timestamptz,
    es_principal boolean not null default false,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    unique (persona_id, tipo, valor)
);

create table public.niveles_notificacion (
    id smallint generated by default as identity primary key,
    codigo varchar(30) not null unique,
    nombre varchar(80) not null
);

insert into public.niveles_notificacion (codigo, nombre) values
    ('ASISTENCIA', 'Asistencia'),
    ('ACTIVIDAD', 'Actividad para casa'),
    ('AVISO_IE', 'Aviso institucional'),
    ('CORRECCION', 'Corrección de registro');

create table public.secciones (
    id bigint generated by default as identity primary key,
    anio_escolar_id bigint not null,
    institucion_id bigint not null,
    grado_id smallint not null,
    sede_id bigint references public.sedes_educativas(id),
    aula_id bigint references public.aulas(id),
    turno_id smallint references public.turnos(id),
    nombre varchar(20) not null,
    capacidad_maxima smallint check (capacidad_maxima is null or capacidad_maxima > 0),
    activa boolean not null default true,
    created_at timestamptz not null default now(),
    foreign key (anio_escolar_id) references public.anios_escolares(id),
    foreign key (institucion_id) references public.instituciones_educativas(id),
    foreign key (grado_id) references public.grados_educativos(id),
    unique (institucion_id, anio_escolar_id, grado_id, nombre)
);

create table public.asignaciones_roles (
    id bigint generated by default as identity primary key,
    cuenta_usuario_id bigint not null references public.cuentas_usuario(id),
    rol_id smallint not null references public.roles(id),
    institucion_id bigint references public.instituciones_educativas(id),
    anio_escolar_id bigint references public.anios_escolares(id),
    seccion_id bigint references public.secciones(id),
    vigente_desde date not null default current_date,
    vigente_hasta date,
    check (vigente_hasta is null or vigente_hasta >= vigente_desde)
);

create table public.vinculos_apoderado_estudiante (
    id bigint generated by default as identity primary key,
    apoderado_id bigint not null references public.apoderados(id),
    estudiante_id bigint not null references public.estudiantes(id),
    parentesco varchar(40),
    puede_consultar boolean not null default true,
    recibe_notificaciones boolean not null default true,
    vigente_desde date not null default current_date,
    vigente_hasta date,
    verificado_at timestamptz,
    check (vigente_hasta is null or vigente_hasta >= vigente_desde),
    unique (apoderado_id, estudiante_id, vigente_desde)
);

create table public.matriculas (
    id bigint generated by default as identity primary key,
    estudiante_id bigint not null references public.estudiantes(id),
    anio_escolar_id bigint not null,
    institucion_id bigint not null,
    fecha_matricula date not null default current_date,
    estado varchar(24) not null default 'ACTIVA'
        check (estado in ('ACTIVA', 'TRASLADADA', 'RETIRADA', 'CERRADA')),
    created_at timestamptz not null default now(),
    foreign key (anio_escolar_id) references public.anios_escolares(id),
    foreign key (institucion_id) references public.instituciones_educativas(id),
    unique (estudiante_id, anio_escolar_id)
);

create table public.ubicaciones_matricula (
    id bigint generated by default as identity primary key,
    matricula_id bigint not null references public.matriculas(id),
    seccion_id bigint not null references public.secciones(id),
    fecha_inicio date not null,
    fecha_fin date,
    motivo varchar(40) not null default 'MATRICULA_INICIAL',
    created_at timestamptz not null default now(),
    check (fecha_fin is null or fecha_fin >= fecha_inicio),
    unique (matricula_id, fecha_inicio)
);

create unique index uq_ubicacion_matricula_vigente
    on public.ubicaciones_matricula (matricula_id)
    where fecha_fin is null;

create table public.movimientos_matricula (
    id bigint generated by default as identity primary key,
    matricula_id bigint not null references public.matriculas(id),
    tipo varchar(30) not null check (tipo in ('CAMBIO_SECCION', 'TRASLADO', 'RETIRO', 'REINCORPORACION')),
    fecha_efectiva date not null,
    motivo text,
    registrado_por bigint references public.cuentas_usuario(id),
    created_at timestamptz not null default now()
);

create table public.asignaciones_docentes (
    id bigint generated by default as identity primary key,
    cuenta_usuario_id bigint not null references public.cuentas_usuario(id),
    seccion_id bigint not null references public.secciones(id),
    es_tutor boolean not null default false,
    vigente_desde date not null default current_date,
    vigente_hasta date,
    check (vigente_hasta is null or vigente_hasta >= vigente_desde),
    unique (cuenta_usuario_id, seccion_id, vigente_desde)
);

create unique index uq_tutor_vigente_seccion
    on public.asignaciones_docentes (seccion_id)
    where es_tutor and vigente_hasta is null;

create table public.jornadas_asistencia (
    id bigint generated by default as identity primary key,
    seccion_id bigint not null references public.secciones(id),
    fecha date not null,
    estado varchar(20) not null default 'BORRADOR'
        check (estado in ('BORRADOR', 'CONFIRMADA', 'CORREGIDA')),
    registrada_por bigint not null references public.cuentas_usuario(id),
    confirmada_por bigint references public.cuentas_usuario(id),
    confirmada_at timestamptz,
    created_at timestamptz not null default now(),
    unique (seccion_id, fecha),
    check ((estado = 'BORRADOR' and confirmada_at is null) or
           (estado in ('CONFIRMADA', 'CORREGIDA') and confirmada_at is not null))
);

create table public.registros_asistencia (
    id bigint generated by default as identity primary key,
    jornada_id bigint not null references public.jornadas_asistencia(id),
    ubicacion_matricula_id bigint not null references public.ubicaciones_matricula(id),
    estado varchar(30) not null check (estado in (
        'SIN_REGISTRAR', 'PRESENTE', 'AUSENTE', 'TARDANZA', 'AUSENCIA_JUSTIFICADA'
    )),
    observacion text,
    registrado_at timestamptz not null default now(),
    unique (jornada_id, ubicacion_matricula_id)
);
